spring:
  application:
    name: MenuDisplay
  datasource:
    url: jdbc:mysql://localhost:3306/newmenu
    username: root
    password: Divyapass@23
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true